apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-statsd-exporter.fullname" . }}
  labels:
    {{- include "prometheus-statsd-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.webEnabled }}
    - name: web
      port: {{ .Values.webPort }}
      protocol: TCP
      targetPort: {{ .Values.webPort }}
    {{- end }}
    {{- if .Values.service.udpEnabled }}
    - name: statsd-udp
      port: {{ .Values.udpPort }}
      protocol: UDP
      targetPort: {{ .Values.udpPort }}
    {{- end }}
    {{- if .Values.service.tcpEnabled }}
    - name: statsd-tcp
      port: {{ .Values.tcpPort }}
      protocol: TCP
      targetPort: {{ .Values.tcpPort }}
    {{- end }}
  selector:
    {{- include "prometheus-statsd-exporter.selectorLabels" . | nindent 4 }}
