apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-statsd-exporter.fullname" . }}-web
  labels:
    {{- include "prometheus-statsd-exporter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: statsd-web
      port: {{ .Values.webPort }}
      protocol: TCP
      targetPort: {{ .Values.webPort }}
  selector:
    {{- include "prometheus-statsd-exporter.selectorLabels" . | nindent 4 }}
